INSERT INTO fishes (fishtype_id,fish_name) VALUES 
(4,'Abrótea'),
(4,'Ariacó'),
(4,'Badejo / Sirigado'),
(4,'Bagre'),
(4,'Batata'),
(4,'Batata-da-pedra'),
(4,'Besugo'),
(4,'Bijupirá'),
(4,'Biquara / Corcoroca / Pirambú'),
(4,'Budião'),
(4,'Cação bagre'),
(4,'Cação gato'),
(4,'Caranguejo aranha'),
(4,'Caranguejo real'),
(4,'Caranguejo vermelho'),
(4,'Caranha'),
(4,'Carapitanga / Paramirim / Realito'),
(4,'Caraúna / Cirurgião'),
(4,'Cherne galha-amarela'),
(4,'Cherne listrado'),
(4,'Cherne poveiro'),
(4,'Cherne queimado'),
(4,'Cherne verdadeiro'),
(4,'Cioba / Sirioba'),
(4,'Congro'),
(4,'Congro negro'),
(4,'Congro rosa'),
(4,'Dentão / Baúna'),
(4,'Garoupa gato'),
(4,'Garoupa verdadeira'),
(4,'Garoupa vermelha / São-Tomé'),
(4,'Gostosa / Piranema'),
(4,'Guaiúba / rabo-amarelo'),
(4,'Jaguariçá'),
(4,'Lagosta pintada'),
(4,'Lagosta sapateira'),
(4,'Lagosta verde'),
(4,'Lagosta vermelha'),
(4,'Mariquita'),
(4,'Moréia'),
(4,'Namorado'),
(4,'Olho-de-cão'),
(4,'Pargo boca-preta / Sassupema'),
(4,'Pargo olho-amarelo'),
(4,'Pargo olhudo'),
(4,'Pargo rosa'),
(4,'Pargo verdadeiro'),
(4,'Peixe pena'),
(4,'Peixe porco / Peroá / Cangulo'),
(4,'Piraúna / Catuá / Jabú'),
(4,'Polvo'),
(4,'Salema'),
(4,'Saramunete'),
(4,'Sarrão '),
(4,'Trilha'),

(11,'Abrótea'),
(11,'Bagre'),
(11,'Batata'),
(11,'Cabrinha'),
(11,'Cação anjo'),
(11,'Cação bagre'),
(11,'Cação bico-doce'),
(11,'Cação cola-fina'),
(11,'Cação mangona'),
(11,'Calamar'),
(11,'Camarão Barab-Ruça / Ferrinho'),
(11,'Camarão Branco / Legítimo'),
(11,'Camarão Carabineiro'),
(11,'Camarão Rosa'),
(11,'Camarão Sete Barbas'),
(11,'Camarão vermelho / Santana'),
(11,'Caranguejo real '),
(11,'Caranguejo vermelho'),
(11,'Castanha'),
(11,'Congro'),
(11,'Congro rosa'),
(11,'Corvina'),
(11,'Linguado'),
(11,'Lula'),
(11,'Merluza'),
(11,'Palombeta'),
(11,'Pargo rosa'),
(11,'Peixe porco / Peroá'),
(11,'Peixe-sapo'),
(11,'Pescada amarela'),
(11,'Pescada branca'),
(11,'Pescada cambucu'),
(11,'Pescada foguete'),
(11,'Pescada gó'),
(11,'Pescada goete'),
(11,'Pescada olhuda / Maria-mole'),
(11,'Pescadinha'),
(11,'Pescadinha real'),
(11,'Polvo'),
(11,'Raia emplasto'),
(11,'Trilha'),
(11,'Viola'),

(9,'Abrótea'),
(9,'Abrótea-do-fundo'),
(9,'Badejo'),
(9,'Barracuda'),
(9,'Batata'),
(9,'Batata-da-pedra'),
(9,'Cabrinha'),
(9,'Cação anjo'),
(9,'Cação bagre'),
(9,'Cação bico-doce'),
(9,'Cação frango'),
(9,'Cação-de-espinho'),
(9,'Cação machote'),
(9,'Cação mangona'),
(9,'Cavala'),
(9,'Catuá / Garoupinha'),
(9,'Cherne verdadeiro'),
(9,'Cherne galha-amarela'),
(9,'Cherne queimado'),
(9,'Cherne listrado'),
(9,'Cherne poveiro'),
(9,'Cioba / Sirioba'),
(9,'Congro'),
(9,'Congro rosa'),
(9,'Corvina'),
(9,'Dentão'),
(9,'Dourado'),
(9,'Garoupa verdadeira'),
(9,'Garoupa vermelha / São-Tomé'),
(9,'Guaiúba / rabo-amarelo'),
(9,'Lírio'),
(9,'Merluza'),
(9,'Mero'),
(9,'Namorado'),
(9,'Olhete / Pitangola'),
(9,'Olho-de-boi'),
(9,'Olho-de-cão'),
(9,'Pargo verdadeiro'),
(9,'Pargo rosa'),
(9,'Peixe pena'),
(9,'Peixe porco / Peroá / Cangulo'),
(9,'Raia'),
(9,'Vermelho'),
(9,'Vermelho olho-amarelo'),
(9,'Viola'),
(9,'Sarrão'),
(9,'Xaréu / Xarelete / Carapau'),

(3,'Abrótea'),
(3,'Abrótea-do-fundo'),
(3,'Badejo quadrado'),
(3,'Badejo mira'),
(3,'Barracuda'),
(3,'Bicuda'),
(3,'Batata'),
(3,'Batata-da-pedra'),
(3,'Bonito pintado'),
(3,'Cação anequim / moro'),
(3,'Cação anjo'),
(3,'Cação azul / mole-mole'),
(3,'Cação bagre'),
(3,'Cação bico-doce'),
(3,'Cação cabeça-chata'),
(3,'Cação cola-fina'),
(3,'Cação-de-espinho'),
(3,'Cação frango'),
(3,'Cação martelo'),
(3,'Cação machote'),
(3,'Cação mangona'),
(3,'Cação viola'),
(3,'Caranha'),
(3,'Catuá / Garoupinha'),
(3,'Cavala'),
(3,'Cavala empinge'),
(3,'Cherne verdadeiro'),
(3,'Cherne galha amarela'),
(3,'Cherne queimado'),
(3,'Cherne listrado'),
(3,'Cherne poveiro'),
(3,'Cioba'),
(3,'Congro'),
(3,'Congro'),
(3,'Dentão'),
(3,'Dourado'),
(3,'Enchova'),
(3,'Espada'),
(3,'Garoupa verdadeira'),
(3,'Garoupa São-Tomé'),
(3,'Guaiúba'),
(3,'Lírio'),
(3,'Mero'),
(3,'Namorado'),
(3,'Olho-de-boi'),
(3,'Olhete / Pitangola'),
(3,'Pargo rosa'),
(3,'Peixe porco / Peroá'),
(3,'Raia'),
(3,'Realito'),
(3,'Sarrão'),
(3,'Vermelho'),
(3,'Xaréu'),
(3,'Xarelete / Carapau'),

(7,'Albacora-bandolim (BET)'),
(7,'Albacora-branca (ALB)'),
(7,'Albacora laje (YFT)'),
(7,'Albacorinha (BLF)'),
(7,'Bicuda'),
(7,'Bonito Cachorro'),
(7,'Bonito Listrado'),
(7,'Bonito Pintado'),
(7,'Cavala'),
(7,'Cavala Empinge (W AH)'),
(7,'Dourado (DOL)'),

(1,'Albacora-bandolim (BET)'),
(1,'Albacora-branca (ALB)'),
(1,'Albacora-laje (YFT)'),
(1,'Albacorinha (BLF)'),
(1,'Bonito-cachorro'),
(1,'Bonito-listrado (SKJ)'),
(1,'Bonito-pintado'),
(1,'Cavala'),
(1,'Cavala-empinge (W AH)'),
(1,'Dourado (DOL)'),

(5,'Anchoíta'),
(5,'Bicuda'),
(5,'Bonito cachorro'),
(5,'Bonito pintado'),
(5,'Carapau'),
(5,'Cavalinha'),
(5,'Corvina'),
(5,'Dourado'),
(5,'Enchova'),
(5,'Espada'),
(5,'Peixe'),
(5,'Galo'),
(5,'Goete'),
(5,'Gordinho'),
(5,'Palombeta'),
(5,'Pescada'),
(5,'Pescadinha'),
(5,'Sarda'),
(5,'Sardinha boca-torta'),
(5,'Sardinha cascuda'),
(5,'Sardinha laje'),
(5,'Sardinha verdadeira'),
(5,'Savelha'),
(5,'Serra/Sororoca'),
(5,'Tainha'),
(5,'Xaréu'),
(5,'Xerelete'),
(5,'Xixarro'),

(10,'Cação galha-branca'),
(10,'Cação galha-preta'),
(10,'Cação galhudo'),
(10,'Cação lombo preto'),
(10,'Cação machote'),
(10,'Cação mangona'),
(10,'Cação martelo'),
(10,'Cação martelo-liso'),
(10,'Cação tigre / Tintureiro'),
(10,'Cavala'),
(10,'Cavala empinge'),
(10,'Dourado'),
(10,'Espadarte / Meca'),
(10,'Olho-de-boi / Arabaiana'),
(10,'Peixe lua'),
(10,'Peixe prego'),
(10,'Raia lixa'),
(10,'Raia manteiga'),
(10,'Raia chita'),
(10,'Raia manta'),
(10,'Sarda'),
(10,'Serra / Sororoca'),
(10,'Xaréu'),

(8,'Agulhão branco (WHM)'),
(8,'Agulhão negro (BUM)'),
(8,'Agulhão vela (SAI)'),
(8,'Albacora Azul (BFT)'),
(8,'Albacora bandolim (BET)'),
(8,'Albacora branca (ALB)'),
(8,'Albacora laje (YFT)'),
(8,'Albacorinha (BLF)'),
(8,'Arraia jamanta'),
(8,'Barracuda'),
(8,'Cavala empinge (W AH)'),
(8,'Cavala preta'),
(8,'Dourado (DOL)'),
(8,'Espadarte (SWO)'),
(8,'Peixe prego'),
(8,'Tubarão azul (BSH)'),
(8,'Tubarão cachorro'),
(8,'Tubarão lombo preto (FAL)'),
(8,'Tubarão mako / anequim (MAK)'),
(8,'Tubarão martelo(SPX)'),
(8,'Tubarão raposa (BTH)'),
(8,'Tubarão tigre'),

(2,'Calamar argentino'),
(2,'Lula comum'),
(2,'Outras'),

(6,'Arabaiana'),
(6,'Aracanguira'),
(6,'Ariacó'),
(6,'Sirigado'),
(6,'Barracuda / Goirana'),
(6,'Batata'),
(6,'Batata-da-pedra'),
(6,'Biquara / Pirambú'),
(6,'Bijupirá'),
(6,'Cação / Tubarão'),
(6,'Cação martelo'),
(6,'Cangulo / Peroá'),
(6,'Caranha'),
(6,'Carapitanga / Paramirim'),
(6,'Cavala'),
(6,'Cavala empinge'),
(6,'Cioba / Sirioba'),
(6,'Corvina'),
(6,'Cherne verdadeiro'),
(6,'Cherne galha-amarela'),
(6,'Cherne queimado'),
(6,'Cherne listrado'),
(6,'Dentão'),
(6,'Dourado'),
(6,'Graçarim / Guaracimbora'),
(6,'Garoupa'),
(6,'Garoupa gato'),
(6,'Gostosa / Piranema'),
(6,'Guaiúba / rabo-amarelo'),
(6,'Guaricema / Guarassuma'),
(6,'Guarajuba'),
(6,'Gurijuba'),
(6,'Mero / Canapú'),
(6,'Olho-de-boi'),
(6,'Pargo verdadeiro'),
(6,'Pargo olho-amarelo'),
(6,'Pargo boca-preta / Sassupema'),
(6,'Pargo olhudo'),
(6,'Peixe pena'),
(6,'Pescada Amarela'),
(6,'Pirá'),
(6,'Piraúna / Jabú / Catuá'),
(6,'Raia'),
(6,'Xaréu'),
(6,'Xaréu preto'),

(12,'Abrótea'),
(12,'Bagre'),
(12,'Baiacu'),
(12,'Batata'),
(12,'Batata-da-Pedra'),
(12,'Betara / Papa-terra'),
(12,'Cabrinha'),
(12,'Cação bagre'),
(12,'Cação bico-doce'),
(12,'Cação cola-fina'),
(12,'Cação mangona'),
(12,'Cação anjo'),
(12,'Calamar argentino'),
(12,'Camarão barba-ruça / ferrinho'),
(12,'Camarão branco / legítimo'),
(12,'Camarão carabineiro'),
(12,'Camarão rosa'),
(12,'Camarão sete barbas'),
(12,'Camarão vermelho / Santana'),
(12,'Caranguejo real'),
(12,'Caranguejo vermelho'),
(12,'Castanha'),
(12,'Cavalinha'),
(12,'Cherne-poveiro'),
(12,'Cherne-verdadeiro'),
(12,'Cherne galha-amarela'),
(12,'Congro-rosa'),
(12,'Corvina'),
(12,'Espada'),
(12,'Galo'),
(12,'Garoupa'),
(12,'Goete'),
(12,'Guaivira'),
(12,'Linguado'),
(12,'Lula'),
(12,'Merluza'),
(12,'Namorado'),
(12,'Pargo rosa'),
(12,'Peixe-porco / Peroá'),
(12,'Peixe-sapo'),
(12,'Pescada amarela'),
(12,'Pescada branca'),
(12,'Pescada cambucu'),
(12,'Pescada foguete'),
(12,'Pescada olhuda/Maria-mole'),
(12,'Pescadinha real'),
(12,'Polvo'),
(12,'Raias'),
(12,'Roncador'),
(12,'Sarrão'),
(12,'Trilha'),
(12,'Viola'),
(12,'Xixarro');